services:
  jupyter:
    build: ./jupyter
    ports:
      - 8888:8888
    volumes:
      - jupyter_data:/src

volumes:
  jupyter_data:
    driver: local
    driver_opts:
      type: none
      device: ./jupyter
      o: bind
